# -*- coding: utf-8 -*-
"""
gen_adders.py — 一键生成 HalfAdder / FullAdder (1-bit) Verilog 模块

用法：
  python gen_adders.py
  python gen_adders.py --out adders.v
  python gen_adders.py --sv --out adders.sv
  python gen_adders.py --prefix My --out my_adders.v   # 生成 MyHalfAdder / MyFullAdder

默认输出：
  - HalfAdder(a,b,sum,carry)
  - FullAdder(a,b,cin,sum,carry)
"""

import argparse
from pathlib import Path


def verilog_text(prefix: str = "", use_sv: bool = False) -> str:
    HA = f"{prefix}HalfAdder"
    FA = f"{prefix}FullAdder"

    # 纯组合逻辑：最兼容、最快速
    body = f"""// ---- Auto-generated by gen_adders.py ----


// 1-bit Half Adder
module {HA} (
  input  wire a,
  input  wire b,
  output wire sum,
  output wire carry
);
  assign sum   = a ^ b;
  assign carry = a & b;
endmodule

// 1-bit Full Adder
module {FA} (
  input  wire a,
  input  wire b,
  input  wire cin,
  output wire sum,
  output wire carry
);
  assign sum   = a ^ b ^ cin;
  assign carry = (a & b) | (a & cin) | (b & cin);
endmodule


"""
    if use_sv:
        # SV 版本主要是语法更宽松；你项目若全用 .sv 可以开这个
        body = body.replace("module ", "module ").replace("wire ", "logic ")
        # 不改端口名，保证与你 gen_wallace 生成的实例一致
    return body


def main():
    ap = argparse.ArgumentParser(description="Generate HalfAdder/FullAdder Verilog modules.")
    ap.add_argument("--out", type=str, default="adders.v", help="output file name (default: adders.v)")
    ap.add_argument("--sv", action="store_true", help="emit SystemVerilog-friendly code (.sv style)")
    ap.add_argument("--prefix", type=str, default="", help="module name prefix (e.g. 'My' -> MyHalfAdder)")
    ap.add_argument("--force", action="store_true", help="overwrite if file exists")
    args = ap.parse_args()

    out_path = Path(args.out).resolve()
    if out_path.exists() and not args.force:
        raise SystemExit(f"[ERROR] {out_path.name} already exists. Use --force to overwrite.")

    text = verilog_text(prefix=args.prefix, use_sv=args.sv)
    out_path.write_text(text, encoding="utf-8")
    print(f"[OK] Generated: {out_path}")


if __name__ == "__main__":
    main()
